/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CardId = Uint8Array;
export type Col = string;
export type CreatedAt = string;
export type CreatedBy = string;
export type Login = string;
export type PersonName = string;
export type ShiftCoHost = string;
export type ShiftPattern = string;
export interface StaffingCard {
  'id' : CardId,
  'col' : Col,
  'shiftCoHost' : ShiftCoHost,
  'createdAt' : CreatedAt,
  'createdBy' : CreatedBy,
  'personName' : PersonName,
  'login' : Login,
  'shiftPattern' : ShiftPattern,
}
export type Term = string;
export type Title = string;
export interface UniversityCard {
  'id' : CardId,
  'col' : Col,
  'title' : Title,
  'createdAt' : CreatedAt,
  'createdBy' : CreatedBy,
  'term' : Term,
}
export interface _SERVICE {
  'getAllStaffingCards' : ActorMethod<[], Array<StaffingCard>>,
  'getAllUniversityCards' : ActorMethod<[], Array<UniversityCard>>,
  'getLastUpdated' : ActorMethod<[], string>,
  'saveAllStaffingCards' : ActorMethod<[Array<StaffingCard>], undefined>,
  'saveAllUniversityCards' : ActorMethod<[Array<UniversityCard>], undefined>,
  'setLastUpdated' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];