/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardId = IDL.Vec(IDL.Nat8);
export const Col = IDL.Text;
export const ShiftCoHost = IDL.Text;
export const CreatedAt = IDL.Text;
export const CreatedBy = IDL.Text;
export const PersonName = IDL.Text;
export const Login = IDL.Text;
export const ShiftPattern = IDL.Text;
export const StaffingCard = IDL.Record({
  'id' : CardId,
  'col' : Col,
  'shiftCoHost' : ShiftCoHost,
  'createdAt' : CreatedAt,
  'createdBy' : CreatedBy,
  'personName' : PersonName,
  'login' : Login,
  'shiftPattern' : ShiftPattern,
});
export const Title = IDL.Text;
export const Term = IDL.Text;
export const UniversityCard = IDL.Record({
  'id' : CardId,
  'col' : Col,
  'title' : Title,
  'createdAt' : CreatedAt,
  'createdBy' : CreatedBy,
  'term' : Term,
});

export const idlService = IDL.Service({
  'getAllStaffingCards' : IDL.Func([], [IDL.Vec(StaffingCard)], ['query']),
  'getAllUniversityCards' : IDL.Func([], [IDL.Vec(UniversityCard)], ['query']),
  'getLastUpdated' : IDL.Func([], [IDL.Text], ['query']),
  'saveAllStaffingCards' : IDL.Func([IDL.Vec(StaffingCard)], [], []),
  'saveAllUniversityCards' : IDL.Func([IDL.Vec(UniversityCard)], [], []),
  'setLastUpdated' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardId = IDL.Vec(IDL.Nat8);
  const Col = IDL.Text;
  const ShiftCoHost = IDL.Text;
  const CreatedAt = IDL.Text;
  const CreatedBy = IDL.Text;
  const PersonName = IDL.Text;
  const Login = IDL.Text;
  const ShiftPattern = IDL.Text;
  const StaffingCard = IDL.Record({
    'id' : CardId,
    'col' : Col,
    'shiftCoHost' : ShiftCoHost,
    'createdAt' : CreatedAt,
    'createdBy' : CreatedBy,
    'personName' : PersonName,
    'login' : Login,
    'shiftPattern' : ShiftPattern,
  });
  const Title = IDL.Text;
  const Term = IDL.Text;
  const UniversityCard = IDL.Record({
    'id' : CardId,
    'col' : Col,
    'title' : Title,
    'createdAt' : CreatedAt,
    'createdBy' : CreatedBy,
    'term' : Term,
  });
  
  return IDL.Service({
    'getAllStaffingCards' : IDL.Func([], [IDL.Vec(StaffingCard)], ['query']),
    'getAllUniversityCards' : IDL.Func(
        [],
        [IDL.Vec(UniversityCard)],
        ['query'],
      ),
    'getLastUpdated' : IDL.Func([], [IDL.Text], ['query']),
    'saveAllStaffingCards' : IDL.Func([IDL.Vec(StaffingCard)], [], []),
    'saveAllUniversityCards' : IDL.Func([IDL.Vec(UniversityCard)], [], []),
    'setLastUpdated' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };